In [ ]:
!pip install torch torchvision transformers datasets pillow tiktoken sentencepiece

Requirement already satisfied: torch in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (2.8.0)
Requirement already satisfied: torchvision in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (0.23.0)
Requirement already satisfied: transformers in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (4.56.0)
Requirement already satisfied: datasets in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (4.1.1)
Requirement already satisfied: pillow in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (11.3.0)
Requirement already satisfied: tiktoken in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (0.11.0)
Requirement already satisfied: sentencepiece in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (0.2.1)
Requirement already satisfied: filelock in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (78.1.1)
Requirement already satisfied: sympy>=1.13.3 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (2025.7.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torch) (3.4.0)
Requirement already satisfied: numpy in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from torchvision) (2.3.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from transformers) (0.34.4)
Requirement already satisfied: packaging>=20.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from transformers) (2025.8.29)
Requirement already satisfied: requests in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from transformers) (0.22.0)
Requirement already satisfied: safetensors>=0.4.3 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from transformers) (4.67.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.9)
Requirement already satisfied: pyarrow>=21.0.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from datasets) (2.3.2)
Requirement already satisfied: xxhash in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.12.15)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (6.6.4)
Requirement already satisfied: propcache>=0.2.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (1.20.1)
Requirement already satisfied: idna>=2.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets) (3.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from requests->transformers) (2025.8.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /home/manav/miniconda3/envs/jupyter_env/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [2]:
import pandas as pd

# Load each file and add a 'niche' column
fashion = pd.read_csv("fashion_full.csv")
beauty = pd.read_csv("Beauty&PersonalCare_full.csv")
electronics = pd.read_csv("ConsumerElectronics_full.csv")
health = pd.read_csv("Health&Supplements_full.csv")
jewellery = pd.read_csv("Jewellery_full.csv")
baby = pd.read_csv("Baby&Kids_full.csv")
hobbies = pd.read_csv("Hobbies&Collectibles_full.csv")
home = pd.read_csv("Home&Interior_full.csv")
lighting = pd.read_csv("Lights_full.csv")
office = pd.read_csv("OfficeSupplies_full.csv")
others = pd.read_csv("Others_full.csv")
outdoor = pd.read_csv("Outdoor,Garden&AdventureGear_full.csv")
sports = pd.read_csv("Sports&FitnessEquipment_full.csv")

In [3]:
fashion = fashion.sample(frac=1, random_state=42).reset_index(drop=True)
beauty = beauty.sample(frac=1, random_state=42).reset_index(drop=True)
electronics = electronics.sample(frac=1, random_state=42).reset_index(drop=True)
health = health.sample(frac=1, random_state=42).reset_index(drop=True)
jewellery = jewellery.sample(frac=1, random_state=42).reset_index(drop=True)
baby = baby.sample(frac=1, random_state=42).reset_index(drop=True)
hobbies = hobbies.sample(frac=1, random_state=42).reset_index(drop=True)
home = home.sample(frac=1, random_state=42).reset_index(drop=True)
lighting = lighting.sample(frac=1, random_state=42).reset_index(drop=True)
office = office.sample(frac=1, random_state=42).reset_index(drop=True)
others = others.sample(frac=1, random_state=42).reset_index(drop=True)
outdoor = outdoor.sample(frac=1, random_state=42).reset_index(drop=True)
sports = sports.sample(frac=1, random_state=42).reset_index(drop=True)

In [4]:
lighting = lighting.drop_duplicates(subset=['src'])
fashion=fashion.drop_duplicates(subset=['title'])

In [5]:
fashion.head()

,product_id,title,src,classified_niche_ai
0,3997039,Maria | Elegant and trendy fleece jacket,https://cdn.shopify.com/s/files/1/0906/4313/68...,Fashion
1,3456269,Comfortable Ladies Cardigan - Luna,https://cdn.shopify.com/s/files/1/0873/7610/16...,Fashion
2,4062694,Damen Jumpsuit mit V-Ausschnitt,https://cdn.shopify.com/s/files/1/0890/2652/75...,Fashion
3,2189050,Perugia ClassicHose,https://cdn.shopify.com/s/files/1/0825/5812/43...,Fashion
4,4029133,Sol&egrave;ne &ndash; &Auml;rmelloses Boho-Som...,https://cdn.shopify.com/s/files/1/0725/6686/62...,Fashion

In [ ]:
fashion=fashion.drop_duplicates(subset=['src'])[:50]
beauty = beauty.drop_duplicates(subset=['src'])[:50]
electronics = electronics.drop_duplicates(subset=['src'])[:50]
electronics = electronics.drop_duplicates(subset=['src'])[:50]
health = health.drop_duplicates(subset=['src'])[:50]
jewellery = jewellery.drop_duplicates(subset=['src'])[:50]
baby = baby.drop_duplicates(subset=['src'])[:50]
hobbies = hobbies.drop_duplicates(subset=['src'])[:25]
home = home.drop_duplicates(subset=['src'])[:50]
lighting = lighting.drop_duplicates(subset=['src'])[:50]
office = office.drop_duplicates(subset=['src'])[:25]
others = others.drop_duplicates(subset=['src'])[:50]
outdoor = outdoor.drop_duplicates(subset=['src'])[:50]
sports = sports.drop_duplicates(subset=['src'])[:50]
home=home[:50]
lighting=lighting[:50]
# 3.5 lakh

In [9]:
print(fashion.shape)
print(beauty.shape)
print(electronics.shape)
print(health.shape)
print(jewellery.shape)
print(baby.shape)
print(hobbies.shape)
print(home.shape)
print(lighting.shape)
print(office.shape)
print(others.shape)
print(outdoor.shape)
print(sports.shape)

(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(2500, 4)
(5000, 4)
(5000, 4)
(2500, 4)
(5000, 4)
(5000, 4)
(5000, 4)

In [10]:
stationary=pd.concat([hobbies, office], ignore_index=True)
stationary.head()
stationary['classified_niche_ai']='Hobbies & Stationary Supplies';
stationary.head()

,src,product_id,title,classified_niche_ai
0,https://cdn.shopify.com/s/files/1/0809/8725/92...,3700590,Prick Pack&trade; Embroidery Needles Set,Hobbies & Stationary Supplies
1,https://cdn.shopify.com/s/files/1/0743/1454/74...,2835908,ArtistryPro - 24 teiliges K&uuml;nstlerpinsel ...,Hobbies & Stationary Supplies
2,https://cdn.shopify.com/s/files/1/0914/0866/29...,3715057,SewSwift&trade; &mdash; Thread Needles Instant...,Hobbies & Stationary Supplies
3,https://cdn.shopify.com/s/files/1/0846/0743/50...,4563484,Button Craft Power Pack &mdash; Effortlessly S...,Hobbies & Stationary Supplies
4,https://cdn.shopify.com/s/files/1/0904/4590/62...,3576876,Spinning Keychain Fidget,Hobbies & Stationary Supplies

In [11]:
print(fashion.shape)
print(beauty.shape)
print(electronics.shape)
print(health.shape)
print(jewellery.shape)
print(baby.shape)
print(home.shape)
print(lighting.shape)
print(others.shape)
print(outdoor.shape)
print(sports.shape)
print(stationary.shape)

(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)
(5000, 4)

In [12]:
df = pd.concat([fashion, beauty, electronics, stationary, health, jewellery, baby, home, lighting, others, outdoor, sports], ignore_index=True)

In [13]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [14]:
df.to_csv("all_products50.csv", index=False)
df

,product_id,title,src,classified_niche_ai
0,4623941,VersaHold&trade; &ndash; M&uuml;heloser Komfor...,https://cdn.shopify.com/s/files/1/0562/8428/30...,Consumer Electronics
1,4756495,Lumora Trio | LED Nachttischlampe mit Wecker &...,https://cdn.shopify.com/s/files/1/0910/4185/78...,Home & Interior
2,3579393,Rengj&oslash;ringsb&oslash;rste for myk b&osla...,https://cdn.shopify.com/s/files/1/0904/4590/62...,Home & Interior
3,2582354,Sanelya&reg; | CC Cr&egrave;me Ultra Couvrante...,https://cdn.shopify.com/s/files/1/0925/9915/70...,Beauty & Personal Care
4,4693257,Johara - Smooth Silk Serenity Woman's Sleep Ey...,https://cdn.shopify.com/s/files/1/0707/6728/03...,Beauty & Personal Care
...,...,...,...,...
59995,3863923,MILTONAR | VANDRESKO,https://cdn.shopify.com/s/files/1/0912/6674/46...,"Outdoor,Garden & Adventure Gear"
59996,2334262,Taavita Chrome Gold Black Brass Widespread Bat...,https://cdn.shopify.com/s/files/1/0878/1751/94...,Home & Interior
59997,3805786,| Fashionable fitted mini dress with long slee...,https://cdn.shopify.com/s/files/1/0902/0663/43...,Fashion
59998,3454971,Garduru GRATIS | AdjustoBind - Einstellbarer S...,https://cdn.shopify.com/s/files/1/0725/3940/66...,Hobbies & Stationary Supplies
59999,1395459,Max - Trainingspak,https://cdn.shopify.com/s/files/1/0675/8976/74...,Sports & Fitness Equipment

In [15]:
df.isnull().sum()

product_id             0
title                  0
src                    0
classified_niche_ai    0
dtype: int64

In [50]:
df.shape

(2686657, 4)

In [12]:
import pandas as pd
from datasets import Dataset
from PIL import Image
import requests
from io import BytesIO
from transformers import AutoTokenizer, CLIPProcessor

# Load merged CSV
df = pd.read_csv("all_products.csv")   # title, image_link, niche

# Encode labels
labels = df["classified_niche_ai"].unique().tolist()
label2id = {l: i for i, l in enumerate(labels)}
id2label = {i: l for l, i in label2id.items()}
df["label"] = df["classified_niche_ai"].map(label2id)

# Hugging Face Dataset
dataset = Dataset.from_pandas(df)

In [1]:
from datetime import datetime

config = {
    "model_type": "multimodal_classifier",
    "text_model": "microsoft/deberta-v3-small",
    "image_model": "google/siglip2-base-patch16-256",
    "num_labels": 14,
    "max_length": 64,
    "accuracy": 0.9246,
    "macro_f1": 0.7329,
    "test_loss": 0.2450,
    "labels": [
        "Baby & Kids",
        "Beauty & Personal Care", 
        "Consumer Electronics",
        "Fashion",
        "Food & Beverages",
        "Health & Supplements",
        "Hobbies & Collectibles",
        "Home & Interior",
        "Jewelry",
        "Lights",
        "Office Supplies",
        "Others",
        "Outdoor, Garden & Adventure Gear",
        "Sports & Fitness Equipment"
    ],
    "upload_date": datetime.now().isoformat()  # already safe to serialize as string
}

In [2]:
import json

with open("config.json", "w") as f:
    json.dump(config, f, indent=4)